---
title: "EXP2_RT"
date: "2024.03.01"
output:
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}

#rm(list=ls())
#require("knitr") 
#opts_chunk$set(tidy = FALSE, warning = FALSE, message = FALSE, cache = FALSE)
#load libraries
suppressMessages(library("tidyverse")) # to organize data
suppressMessages(library("afex"))  # using 'all_fit' to find appropriate optimizer; and 'mixed' for significance test
suppressMessages(library("lmerTest"))  # to fit data with mixed models
suppressMessages(library("emmeans"))  # emmeans is needed for follow-up tests 
suppressMessages(library("multcomp")) # for advanced control for multiple testing/Type 1 errors. using 'update' for post-hoc comp
suppressMessages(library("ggeffects")) # for plotting (G)LMM results
suppressMessages(library("ez"))
suppressMessages(library('car')) # setting labeled contrasts
suppressMessages(library("ggplot2")) # for plotting
suppressMessages(library("ggsci")) # for setting scientific journal color palettes 
suppressMessages(library("gridExtra")) # for arranging the position of figures
suppressMessages(library("ggpubr")) # using the ggexport
suppressMessages(library("sjPlot")) # using the plot_model, to show random and fixed effects.
suppressMessages(library("glmmTMB")) #required by plot_model when plotting random effects
suppressMessages(library("performance")) # model assumptions & performance, to use check_model for model assumptions
suppressMessages(library("RePsychLing")) #using the rePCA to determine redundant random effects
suppressMessages(library("ggthemes"))#provide theme for plot
suppressMessages(library("patchwork")) 

library(gghalves)
library(ggpubr)
library(rstatix)
library(ggnewscale)
library(ggsignif)
library(reshape2)
library(RColorBrewer)
library(grid)
library(magrittr)

select <- dplyr::select # to avoid clashes with the MASS package

```


```{r loaddata}

raw_data  <- read.csv(file="all_data_eyetracking.csv",head=TRUE) # read data
data_df <- raw_data

```


```{r data cleaning}

data_df        <- data_df %>% filter(ACC != 0) # exclude incorrect response
data_df$RT     <- data_df$RT * 1000 # converting s to ms

# Convert variables to factors
data_df$subid          <- factor(data_df$subid)
data_df$type           <- factor(data_df$type)
data_df$consistency    <- factor(data_df$consistency)
data_df$consistency2   <- factor(data_df$consistency,levels=c('c','i1','i2')) # reorder the levels; consistency2 was computed to avoid errors in emmeans package.

```

```{r desrciping data}

#1. how many subjects remained
data_df %>% group_by(subid) %>% summarize() %>% nrow()

#2. how many trials left for each cell
tn <- data_df %>% group_by(subid,consistency,type) %>% summarize(trialn=length(subid)) %>% ungroup()

min(tn$trialn)# check if any condition has too few trials

#3. check the levels of the factors
levels(data_df$type)
levels(data_df$consistency)
levels(data_df$consistency2)

```



```{r recoding and scaling}

#1. re-coding categorical predictors
# must be Sum instead of sum
contrasts(data_df$type)           <- contr.Sum(levels(data_df$type)) 
contrasts(data_df$consistency)    <- contr.Sum(levels(data_df$consistency))
contrasts(data_df$consistency2)   <- contr.Sum(levels(data_df$consistency2))

#check the new coding approach
contrasts(data_df$type)
contrasts(data_df$consistency)
contrasts(data_df$consistency2)

```

```{r full model}

# First fit the full model
m1.full <- lmer(RT ~ 1 + type * consistency2 + 
                  (1 + type * consistency2 | subid), 
                data = data_df,
                control = lmerControl(optimizer = 'bobyqa',
                                       calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(m1.full)
isSingular(m1.full) # Check for singular fits

```

```{r rePCA1}

# Parameters within the model analyzed using PCA
summary(rePCA(m1.full)) # to see how many random effects are needed. It seems 3 is good enough, not the full 6

model_terms <- model.matrix(m1.full)
p_name   <- colnames(model.matrix(m1.full)) 
par_info <- data.frame('number'=c(1:length(p_name)),'names'=p_name)  

```

```{r full model2}

re_t          <- model.matrix(m1.full)[,2] # random effects of type
re_c          <- model.matrix(m1.full)[,3] # random effects of consisc
re_i1         <- model.matrix(m1.full)[,4] # random effects of consisi1
re_tc         <- model.matrix(m1.full)[,5] # random effects of type:c
re_ti1        <- model.matrix(m1.full)[,6] # random effects of type:i1

#This should be the same as Full model
m1.full2 <- lmer(RT ~ 1  + type * consistency2 +
                 (1 + re_t + re_c + re_i1 +re_tc +re_ti1 | subid), 
                 data = data_df,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(m1.full2)

```


```{r re2 model}

m1.re2 <- lmer(RT ~ 1  + type * consistency2 +
                 (1 + re_ti1 | subid), 
                 data = data_df,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(m1.re2)
isSingular(m1.re2)
summary(rePCA(m1.re2))
save(m1.re2, file = "m1_2res_RT.RData")

```

```{r test}

# Check for differences between this model and the full model, ideally there should be no differences
anova(m1.re2, m1.full, refit = F)

```

```{r sig test}

RT.sig1 <- anova(m1.re2,type = 3, test = 'F', ddf='Satterthwaite')  # F test

RT.sig2 <- mixed(RT ~ 1  + type * consistency2 +
                 (1 + re_ti1| subid), 
                 data = data_df,
                 method = "LRT",
                 check_contrasts = F,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))


RT.sig1
RT.sig2
save(RT.sig2, file = "RT_sig.RData")

```

```{r post-hoc comparisons}

emm_options(lmer.df = "asymptotic") 
emmip(m1.re2, consistency2 ~ type) #simple plotting

# main effect of consistency
emm_RT0 <- emmeans(m1.re2, ~ consistency2)
emm_RT0
update(pairs(emm_RT0), by = NULL, adjust = "holm") 

# simple main effect of type
emm_RT1 <- emmeans(m1.re2, ~ type | consistency2)
emm_RT1
update(pairs(emm_RT1), by = NULL, adjust = "holm") 

# simple main effect of consistency
emm_RT2 <- emmeans(m1.re2, ~consistency2 | type)
emm_RT2
update(pairs(emm_RT2), by = NULL, adjust = "holm") 

```

```{r mean data of paticipant}

description1_df  <- data_df %>% group_by(consistency) %>%
  summarise(des_RT = mean(RT), des_sd = sd(RT))

description2_df  <- data_df %>% group_by(type, consistency) %>%
  summarise(des_RT = mean(RT), des_sd = sd(RT))

mean_df         <- data_df %>% group_by(subid, type, consistency) %>%
  summarise(mean_RT = mean(RT)/1000)

mean_df$consistency <- ifelse(mean_df$consistency == "c", "consistent", 
                              ifelse(mean_df$consistency == "i1",
                                     "inconsistent1",
                                    "inconsistent2"))

print(description1_df)
print(description2_df)
print(mean_df)

```

```{r rain and cloud plot loading data}

mean_df$consistency <- factor(mean_df$consistency)  # Convert independent variables to factors
mean_df$type <- factor(mean_df$type, levels = c("person", "fan"))
# If the ordering of the independent variables is required, specify the levels manually.

```


```{r plotting}

# Pre-work, set up various base parameters
windowsFonts(N=windowsFont("Times New Roman"),A=windowsFont("Arial")) 

p<-ggplot(mean_df, aes(x = type, y = mean_RT, 
                       fill = consistency,color = consistency)) +
# Set the x-axis and y-axis, as well as the legend, fill for the fill, color for the border
  
  scale_y_continuous(limits = c(0.2,1.4),
                     breaks = seq(from=0.2,to=1.4,by=0.2),
                     expand = c(0, 0.1)) +
  labs(x = "Type", y = "Response time(secs)") +
# Set the minimum and maximum values of the x- and y-axes as well as the step size, the expand function is used to create additional space on the set axes
  
  scale_colour_manual(values=c("#F3627B","#e5be79","#3e86b5"),name='consistency')+
  scale_fill_manual(values=c("#F3627B","#e5be79","#3e86b5"),name='consistency')+
# Set the color and fill color, this is a global setting, but you can use the ggnewscale package to set it locally later.
  
  theme(legend.position="right",
        legend.title = element_text(size=10,colour='black',family="A"),
        legend.text = element_text(size=10,colour='black',family="A"),
        legend.key.size=unit(0.5,"cm"),
        # Legend setting
        
        axis.ticks.length = unit(0.1, "cm"),  #轴上刻度长度的设定
        axis.text.x = element_text(size=16,colour='black',family ="A"),
        axis.text.y = element_text(size=16,colour='black',family="A"),
        axis.title.x = element_text(size=20,colour='black',family="A"),
        axis.title.y = element_text(size=20,colour='black',family="A"))
        # Setting of axis title and axis scale text
p

# Custom colors
#mycolor<-c("#e5be79","#3e86b5") 
#p0 <- p+scale_color_manual(values=rev(mycolor)) +
  #scale_fill_manual(values=rev(mycolor))
#p0


# First draw half violin map (geom_half_violin) to get p1:
#Parameter adjustment for half violin map:
#position: position adjustment, here move it horizontally to the right by 0.1;
#side: display which side, “I” stands for left side, “R” stands for right side, default “I”;
#adjust: adjust the bandwidth, here set to 1.2 to make the bandwidth slightly smoother;
#trim: trim the data at the end of the violin map, the default is “T”, that is, the tail will be trimmed to the data range; “F” that does not trim the tail;
p1<-p+geom_half_violin(position=position_nudge(x=0.2,y=0),
                       side='R',adjust=1.2,trim=T,
                       color=NA,alpha=0.8)
p1



# Add scatterplot to the left of the half violin plot and adjust to get p2:
p2<-p1+geom_point(aes
                  (x = as.numeric(type)-0.2,# Scatter position shifted left by 0.15
                   y = mean_RT,
                   color = consistency),
                   position = position_jitter(width =0.03),
                   size =1.0, shape =20,alpha=0.8)
# Adjust the scatter so that the original coincident scatter with the same value is spread out
p2



# Add a box-and-line plot in the middle of the p4 scatter and one-half violin plots to get p5:

p3 <- p2 + new_scale_color()+    
# Use the function to create a new scalecolor, which needs to be placed in front of drawing the boxplot
  
  geom_boxplot(outlier.shape = NA, # Hide the outliers;
               width =0.1,
               alpha=0.7,
               position = position_dodge(width = 0.2))+  # Set the distance between boxes
  scale_colour_manual(values=c("black","black","black"),name='consistency')+
# This step locally sets the outline color of the box plot to black, but leaves the color of the scatter plot unchanged.

  stat_signif(annotations =c("***","*"),
              y_position = c(1.3,1.3),
              xmin = c(0.965,1.965),
              xmax = c(1.035,2.035),
              size = NA,  # the size of the horizontal line, and NA for no horizontal line
              tip_length = c(0,0),  # The length of the vertical lines on the left and right sides
              color="black",
              textsize = 5)  # Size of significance markers


p3


# Remove the gray background, remove the background gridlines, remove the top and right frame lines
p4 <- p3+theme_bw()+   # Automatically optimize the aesthetics of graphics using the bw theme
  theme(panel.grid=element_blank()) +
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank())

### Some bits and pieces of optimized code ###
    #axis.title.x = element_text(vjust = -1),
    #axis.title.y = element_text(vjust = 5),
# Make the x-axis and y-axis axis headings farther away from the axis scales

    #plot.margin = margin(20,45,30,30),
# Resize the canvas, the four parameters are trbl(double, top right, bottom left)
    #legend.position = c(1,0.9))  # Adjust the position of the legend

p4
```

```{r save the plot}

ggsave(p4, filename = "exp2_RT.pdf", dpi = 600,
       width=2800,height=2000,units = "px")
# Saved as a pdf can be convenient to modify the dpi information after (pdf stored as a vector map)

```

```{r combine i1 and i2 as i}

new_df <- data_df
new_df$consistency <- ifelse(data_df$consistency == 'c', 
                             'consistent', 'inconsistent')
new_df$consistency <- factor(new_df$consistency)
new_df$type        <- factor(new_df$type)

contrasts(new_df$type)           <- contr.Sum(levels(new_df$type)) 
contrasts(new_df$consistency)    <- contr.Sum(levels(new_df$consistency))
contrasts(new_df$type)
contrasts(new_df$consistency)

```

```{r full model_combine}

mc.full <- lmer(RT ~ 1 + type * consistency + 
                  (1 + type * consistency | subid), 
                data = new_df,
                control = lmerControl(optimizer = 'bobyqa',
                                       calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(mc.full)
isSingular(mc.full) 

summary(rePCA(mc.full))
model_terms <- model.matrix(mc.full)

```

```{r full combined model2}

re_t2          <- model.matrix(mc.full)[,2] # random effects of type
re_c2          <- model.matrix(mc.full)[,3] # random effects of consis
re_tc2        <- model.matrix(mc.full)[,4] # random effects of type:consis

#This should be the same as Full model
mc.full2 <- lmer(RT ~ 1  + type * consistency +
                 (1 + re_t2 + re_c2 +re_tc2 | subid), 
                 data = new_df,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(mc.full2)

```

```{r re1 combined model}

mc.re1 <- lmer(RT ~ 1  + type * consistency +
                 (1 | subid),
                 data = new_df,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(mc.re1)
isSingular(mc.re1)
summary(rePCA(mc.re1))

anova(mc.re1, mc.full, refit = F)

```

```{r sig test combine}

RT.sig_combine <- mixed(RT ~ 1  + type * consistency +
                       (1 | subid), 
                        data = new_df,
                        method = "LRT",
                        check_contrasts = F,
                        control = lmerControl(optimizer = 'bobyqa',
                                              calc.derivs = F,
                                              optCtrl = list(maxfun = 2e5)))
RT.sig_combine

```

```{r post-hoc combine}

emm_options(lmer.df = "asymptotic") 
emmip(mc.re1, consistency ~ type) #simple plotting

# main effect of consistency
emc_RT0 <- emmeans(mc.re1, ~ consistency)
emc_RT0
update(pairs(emc_RT0), by = NULL, adjust = "holm") 

# simple main effect of consistency
emc_RT2 <- emmeans(mc.re1, ~consistency | type)
emc_RT2
update(pairs(emc_RT2), by = NULL, adjust = "holm") 


description1c_df  <- new_df %>% group_by(consistency) %>%
  summarise(des_RT = mean(RT), des_sd = sd(RT))
description2c_df  <- new_df %>% group_by(type, consistency) %>%
  summarise(des_RT = mean(RT), des_sd = sd(RT))
description1c_df
description2c_df

```
