---
title: "EXP1_pp"
author: "Binjie Yang"
date: "2024-03-16"
output: html_document
---

```{r setup, include=FALSE}

#load libraries
suppressMessages(library("tidyverse")) # to organize data
suppressMessages(library("afex"))  # using 'all_fit' to find appropriate optimizer; and 'mixed' for significance test
suppressMessages(library("lmerTest"))  # to fit data with mixed models
suppressMessages(library("emmeans"))  # emmeans is needed for follow-up tests 
suppressMessages(library("multcomp")) # for advanced control for multiple testing/Type 1 errors. using 'update' for post-hoc comp
suppressMessages(library("ggeffects")) # for plotting (G)LMM results
suppressMessages(library('car')) # setting labeled contrasts
suppressMessages(library("ggplot2")) # for plotting
suppressMessages(library("ggsci")) # for setting scientific journal color palettes 
suppressMessages(library("gridExtra")) # for arranging the position of figures
suppressMessages(library("ggpubr")) # using the ggexport
suppressMessages(library("sjPlot")) # using the plot_model, to show random and fixed effects.
suppressMessages(library("glmmTMB")) #required by plot_model when plotting random effects
suppressMessages(library("performance")) # model assumptions & performance, to use check_model for model assumptions
suppressMessages(library("RePsychLing")) #using the rePCA to determine redundant random effects
suppressMessages(library("ggthemes"))#provide theme for plot
suppressMessages(library("patchwork")) 

library(gghalves)
library(ggpubr)
library(rstatix)
library(ggnewscale)
library(ggsignif)
library(reshape2)
library(RColorBrewer)
library(grid)
library(magrittr)

select <- dplyr::select # to avoid clashes with the MASS package

```


```{r loaddata}

raw_data  <- read.csv(file="data_pp_original.csv",head=TRUE) #read data
data_df <- raw_data

```


```{r data cleaning}

data_df          <- data_df %>% filter(matching != 'mismatch')  #include only match trials
data_df          <- data_df %>% filter(key_resp_3.corr != 0)  #exclude false response
data_df          <- data_df %>% filter(consistency != 'filler')
data_df$RT       <- data_df$key_resp_3.rt * 1000 #s to ms

#variables to factors 
data_df$participant     <- factor(data_df$participant)
data_df$stage           <- factor(data_df$stage, levels = c('baseline', 'adapt'))
data_df$consistency     <- factor(data_df$consistency, levels=c('c','i'))

```


```{r desrciping data}

#1. how many subjects remained
data_df %>% group_by(participant) %>% summarize() %>% nrow()

#2. how many trials left for each cell
tn <- data_df %>% group_by(participant,consistency,stage) %>% summarize(trialn=length(participant)) %>% ungroup()

min(tn$trialn)# check if any condition has too few trials

#3. check the levels of the factors
levels(data_df$stage)
levels(data_df$consistency)

```

2.3 re-coding and scaling predictors
```{r recoding and scaling}

#1. re-coding categorical predictors
# must be Sum instead of sum
contrasts(data_df$stage)           <- contr.Sum(levels(data_df$stage)) 
contrasts(data_df$consistency)    <- contr.Sum(levels(data_df$consistency))

#check the new coding approach
contrasts(data_df$stage)
contrasts(data_df$consistency)

```


```{r full model}

#fit full model 
m1.full <- lmer(RT ~ 1 + stage * consistency + 
                  (1 + stage * consistency | participant), 
                data = data_df,
                control = lmerControl(optimizer = 'bobyqa',
                                       calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(m1.full)
isSingular(m1.full) #check for singular fit

```

```{r rePCA1}

#Analysis of parameters within the model using PCA
summary(rePCA(m1.full)) 
model_terms <- model.matrix(m1.full)

p_name   <- colnames(model.matrix(m1.full)) 
par_info <- data.frame('number'=c(1:length(p_name)),'names'=p_name)  
# must check the column names and get the right column!!! very very important.

```


```{r full model2}

re_s          <- model.matrix(m1.full)[,2] # random effects of stage
re_c          <- model.matrix(m1.full)[,3] # random effects of consis
re_sc         <- model.matrix(m1.full)[,4] # random effects of stage:consis

#This should be the same as Full model
m1.full2 <- lmer(RT ~ 1  + stage * consistency +
                 (1 + re_s + re_c + re_sc | participant), 
                 data = data_df,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(m1.full2)
# Note the careful comparison with the first full model

```


```{r re3 model}

#Retention of the three random effects that explain the most variation
m1.re3 <- lmer(RT ~ 1  + stage * consistency +
                 (1 + re_s + re_c| participant), 
                 data = data_df,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))

summary(m1.re3)
isSingular(m1.re3)
summary(rePCA(m1.re3))
save(m1.re3, file = "pp_m1.re3.RData")

```


```{r test}

#Check for differences between this model and the full model, ideally there should be no differences
anova(m1.re3, m1.full, refit = F)

```


```{r sig test}

RT.sig <- mixed(RT ~ 1  + stage * consistency +
                 (1 + re_s +re_c| participant), 
                 data = data_df,
                 method = "LRT",
                 check_contrasts = F,
                 control = lmerControl(optimizer = 'bobyqa',
                                        calc.derivs = F,
                                       optCtrl = list(maxfun = 2e5)))



RT.sig
save(RT.sig, file = "pp_sig.RData")

```


```{r post-hoc comparisons}

emm_options(lmer.df = "asymptotic") 
emmip(m1.re3, consistency ~ stage) #simple plotting

#main effect of consistency
emm_RT0 <- emmeans(m1.re3, ~ consistency)
emm_RT0
update(pairs(emm_RT0), by = NULL, adjust = "holm") 
confint(pairs(emm_RT0), adjust = "holm")

#simple effect of stage
emm_RT <- emmeans(m1.re3, ~stage | consistency)
emm_RT
update(pairs(emm_RT), by = NULL, adjust = "holm") 
confint(pairs(emm_RT), adjust = "holm")
# using the FDR corrections here

#simple effect of consistency
emm_RT2 <- emmeans(m1.re3, ~consistency | stage)
emm_RT2
update(pairs(emm_RT2), by = NULL, adjust = "holm") 
confint(pairs(emm_RT2), adjust = "holm")

```


```{r mean data of paticipant}

description1_df  <- data_df %>% group_by(consistency) %>%
  summarise(des_RT = mean(RT), des_sd = sd(RT))

description2_df  <- data_df %>% group_by(stage, consistency) %>%
  summarise(des_RT = mean(RT), des_sd = sd(RT))

mean_df         <- data_df %>% group_by(participant, stage, consistency) %>%
  summarise(mean_RT = mean(RT)/1000)

mean_df$consistency <- ifelse(mean_df$consistency == "c", "consistent", "inconsistent")

print(description1_df)
print(description2_df)
print(mean_df)

```


```{r rain and cloud plot loading data}

mean_df$consistency <- factor(mean_df$consistency)  #Convert independent variables to factorials
mean_df$stage <- factor(mean_df$stage, levels = c("baseline", "adapt"))

```


```{r plotting}

#Pre-work, set up various base parameters
windowsFonts(N=windowsFont("Times New Roman"),A=windowsFont("Arial")) 

p<-ggplot(mean_df, aes(x = stage, y = mean_RT, 
                       fill = consistency,color = consistency)) +
# Set the x-axis and y-axis, as well as the legend, fill for the fill, color for the border
  
  scale_y_continuous(limits = c(0.2,1.4),
                     breaks = seq(from=0.2,to=1.4,by=0.2),
                     expand = c(0, 0.1)) +
  labs(x = "Task stage", y = "Response time(secs)") +
# Set the minimum and maximum values of the x- and y-axes as well as the step size, the expand function is used to create additional space on the set axes
  
  scale_colour_manual(values=c("#e5be79","#3e86b5"),name='consistency')+
  scale_fill_manual(values=c("#e5be79","#3e86b5"),name='consistency')+
# Set the color and fill color, this is a global setting, but you can use the ggnewscale package to set it locally later.
  
  theme(legend.position="right",
        legend.title = element_text(size=10,colour='black',family="A"),
        legend.text = element_text(size=10,colour='black',family="A"),
        legend.key.size=unit(0.5,"cm"),
        
        axis.ticks.length = unit(0.1, "cm"),  #轴上刻度长度的设定
        axis.text.x = element_text(size=16,colour='black',family ="A"),
        axis.text.y = element_text(size=16,colour='black',family="A"),
        axis.title.x = element_text(size=20,colour='black',family="A"),
        axis.title.y = element_text(size=20,colour='black',family="A"))

p

#Custom colors
#mycolor<-c("#e5be79","#3e86b5") 
#p0 <- p+scale_color_manual(values=rev(mycolor)) +
  #scale_fill_manual(values=rev(mycolor))
#p0


# First draw half violin map (geom_half_violin) to get p1:
#Parameter adjustment for half violin map:
#position: position adjustment, here move it horizontally to the right by 0.1;
#side: display which side, “I” stands for left side, “R” stands for right side, default “I”;
#adjust: adjust the bandwidth, here set to 1.2 to make the bandwidth slightly smoother;
#trim: trim the data at the end of the violin map, the default is “T”, that is, the tail will be trimmed to the data range; “F” that does not trim the tail;
p1<-p+geom_half_violin(position=position_nudge(x=0.1,y=0),
                       side='R',adjust=1.2,trim=T,color=NA,alpha=0.8)
p1



# Add scatterplot to the left of the half violin plot and adjust to get p2:
p2<-p1+geom_point(aes
                  (x = as.numeric(stage)-0.15,
                   y = mean_RT,
                   color = consistency),
                   position = position_jitter(width =0.03),
                   size =1.0, shape =20, alpha = 0.8)
p2


p3 <- p2 + new_scale_color()+    
  
  geom_boxplot(outlier.shape = NA, 
               width =0.1,
               alpha=0.7,
               position = position_dodge(width = 0.15))+  
  scale_colour_manual(values=c("black","black"),name='consistency')+
  


  stat_signif(annotations =c("***", "n.s."),
              y_position = c(1.35, 1.35),
              xmin = c(0.95, 1.95),
              xmax = c(1.05, 2.05),
              size = NA,  
              tip_length = 0,  
              color="black",
              textsize = 5)  


p3


p4 <- p3+theme_bw()+   
  theme(panel.grid=element_blank()) +
  theme(axis.line = element_line(colour = "black"),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank())
    


p4
```


```{r save the plot}

ggsave(p4, filename = "pp_plot.pdf", dpi = 600,
       width=2800,height=2000,units = "px")

```


```{r effect along the time}

data_df <- data_df %>%
  group_by(participant) %>%
  mutate(trial_num = row_number())

# 计算 RT 差值
calculate_rt_difference_two_quantiles <- function(df) {
  result <- data.frame(participant = character(), stage = character(), quantile_group = integer(), rt_diff = numeric())
  
  # 针对每个参与者进行处理
  for (p in unique(df$participant)) {
    for (s in c("baseline", "adapt")) {
      # 筛选出当前参与者和当前阶段的数据
      participant_stage_data <- subset(df, participant == p & stage == s)
      
      # 按照参与者的 trial_num 划分为两个分位
      participant_stage_data$quantile_group <- cut(participant_stage_data$trial_num, 
                                                  breaks = quantile(participant_stage_data$trial_num, probs = 0:2 / 2), 
                                                  include.lowest = TRUE, labels = FALSE)
      
      # 针对每个分位组计算 RT 差值
      for (q in 1:2) {
        # 获取 consistency 为 i 和 c 的 RT 值
        consistency_i <- subset(participant_stage_data, consistency == "i" & quantile_group == q)$RT
        consistency_c <- subset(participant_stage_data, consistency == "c" & quantile_group == q)$RT
        
        # 如果存在 consistency_i 和 consistency_c 数据，计算差值
        if (length(consistency_i) > 0 && length(consistency_c) > 0) {
          rt_diff <- mean(consistency_i) - mean(consistency_c)
          
          # 将结果添加到数据框
          result <- rbind(result, data.frame(participant = p, stage = s, quantile_group = q, rt_diff = rt_diff))
        } else {
          # 如果缺少数据，跳过当前分位组
          next
        }
      }
    }
  }
  
  return(result)
}

# 计算 RT 差值
rt_diff_result <- calculate_rt_difference_two_quantiles(data_df)

average_rt_diff <- rt_diff_result %>%
  group_by(stage, quantile_group) %>%   # 按stage和quantile_group分组
  summarise(average_rt_diff = mean(rt_diff, na.rm = TRUE))  # 计算平均RT差值，忽略NA值

```

```{r ttest of time course}

# 检验 baseline 和 adapt 两阶段的两分位差异是否显著

# 分别提取 baseline 和 adapt 的数据
baseline_data <- subset(rt_diff_result, stage == "baseline")
adapt_data <- subset(rt_diff_result, stage == "adapt")

# 确保数据按照 participant 和 quantile_group 排序
baseline_data <- baseline_data[order(baseline_data$participant,
                                     baseline_data$quantile_group), ]
adapt_data <- adapt_data[order(adapt_data$participant, adapt_data$quantile_group), ]

# 计算 baseline 的第一分位和第二分位的差异是否显著
baseline_quantile1 <- subset(baseline_data, quantile_group == 1)$rt_diff
baseline_quantile2 <- subset(baseline_data, quantile_group == 2)$rt_diff

baseline_t_test <- t.test(baseline_quantile1, baseline_quantile2, paired = TRUE)
cat("Baseline Stage:\n")
print(baseline_t_test)

# 计算 adapt 的第一分位和第二分位的差异是否显著
adapt_quantile1 <- subset(adapt_data, quantile_group == 1)$rt_diff
adapt_quantile2 <- subset(adapt_data, quantile_group == 2)$rt_diff

adapt_t_test <- t.test(adapt_quantile1, adapt_quantile2, paired = TRUE)
cat("\nAdapt Stage:\n")
print(adapt_t_test)

```


```{r plot exercise effect}


average_rt_diff2 <- rt_diff_result %>%
  group_by(stage, quantile_group) %>%
  summarize(
    average_rt_diff = mean(rt_diff, na.rm = TRUE),
    se = sd(rt_diff, na.rm = TRUE) / sqrt(n())
  )


df.plot <- rt_diff_result %>%
  dplyr::mutate(conds = case_when(stage == "adapt" & quantile_group == "1" ~ "0.88",
                                  stage == "baseline" & quantile_group == "1" ~ "1.12",
                                  stage == "adapt" & quantile_group == "2" ~ "1.88",
                                  stage == "baseline" & quantile_group == "2" ~ "2.12"),
                conds = as.numeric(conds))


s1 <- ggplot(average_rt_diff2, 
       aes(x = factor(quantile_group), 
           y = average_rt_diff, 
           color = stage, 
           group = stage)) +
  geom_line(position = position_dodge(0.5)) +  # 绘制平均值的折线图
  geom_point(size = 3, position = position_dodge(0.5)) +  # 绘制平均值的点
  geom_errorbar(aes(ymin = average_rt_diff - se, ymax = average_rt_diff + se),
                width = 0.1,
                position = position_dodge(0.5)) +  # 绘制误差棒
  # 绘制个体点
  geom_point(data = df.plot,
                      aes(x = conds, y = rt_diff,
                          group = interaction(participant, stage), color = stage),
                          position = position_dodge(0.08),
                          alpha = 0.1) +
  # 绘制个体连线，仅在同一个 stage 内连线
  geom_line(data = df.plot,
                     aes(x = conds, y = rt_diff,
                         group = interaction(participant, stage), color = stage),
                         position = position_dodge(0.08),
                         linetype = 1,
                         size = 0.8,
                         alpha = 0.1) +
  labs(title = "Experiment 1 (person)",
       x = "Time Course",
       y = "Consistency Effect Size",
       color = "Stage") +
  theme_minimal() +  # 使用简洁的主题
  theme(plot.title = element_text(hjust = 0.5)) +  # 标题居中
  scale_x_discrete(labels = c("1st half", "2nd half")) +  # 修改 x 轴标签
  theme(panel.grid = element_blank()) +
  theme(axis.line = element_line(colour = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank())

s1

ggsave(s1, filename = "pp_time_course.pdf", dpi = 600,
       width=4000,height=3000,units = "px")

```